# Generated by Django 5.0.6 on 2024-06-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_cartitem_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
